"""add_notifications_table

Revision ID: 3efcc6d376a9
Revises: 164519420e4d
Create Date: 2026-07-13 07:08:50.433090
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3efcc6d376a9'
down_revision: Union[str, None] = '164519420e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('metadata_', sa.JSON(), nullable=True))
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('notifications', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('ix_notifications_read', table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_column('notifications', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index('ix_notifications_read', 'notifications', ['read'], unique=False)
    op.alter_column('notifications', 'priority',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('notifications', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.drop_column('notifications', 'metadata_')
    # ### end Alembic commands ###
