"""add_account_lifecycle_fields

Revision ID: 4324e58edd79
Revises: 
Create Date: 2026-07-13 06:22:02.998670
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4324e58edd79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=30), nullable=False, server_default='pending_first_login'))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)

    # Backfill status for existing rows based on is_active/is_verified
    op.execute("UPDATE users SET status = 'active' WHERE is_active = true")
    op.execute("UPDATE users SET status = 'disabled' WHERE is_active = false")
    op.execute("UPDATE users SET must_change_password = false WHERE is_verified = true")

    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    # Drop server_defaults after data is populated
    op.alter_column('users', 'status', server_default=None)
    op.alter_column('users', 'must_change_password', server_default=None)
    op.alter_column('users', 'terms_accepted', server_default=None)
    op.alter_column('users', 'profile_completed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # Restore is_active/is_verified from status
    op.execute("UPDATE users SET is_active = true WHERE status = 'active' OR status = 'pending_first_login'")
    op.execute("UPDATE users SET is_active = false WHERE status = 'disabled' OR status = 'locked'")
    op.execute("UPDATE users SET is_verified = true WHERE must_change_password = false")
    op.execute("UPDATE users SET is_verified = false WHERE must_change_password = true")

    op.alter_column('users', 'is_active', nullable=False)
    op.alter_column('users', 'is_verified', nullable=False)

    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'terms_accepted')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'status')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_table('password_history')
    # ### end Alembic commands ###
